# Generated by Django 4.1.1 on 2023-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='register_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
